# Generated by Django 3.2.3 on 2021-05-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
